services:
  db:
    image: mongo
    volumes:
      - db_data:/data/db
    expose:
      - 27017
    profiles:
      - main
  server:
    build: .
    # ties static files so they can be served by the proxy
    volumes:
      - static_files:/backend/static
    expose:
      - 8000
    depends_on:
      - db
    profiles:
      - main
  proxy:
    image: nginx:latest
    volumes:
      - static_files:/backend/static
      - ./nginx.conf:/etc/nginx/nginx.conf # uses custom nginx conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - server
    profiles:
      - main

volumes:
  db_data:
  static_files: