services:
  db:
    image: mongo
    volumes:
      - db_data:/data/db
    expose:
      - 27017
    profiles:
      - main
  server:
#    hostname: uvicorn
    image: username/repository:version
    # ties static files so they can be served by the proxy
    env_file: .env
    volumes:
      - static_files:/backend/static
    expose:
      - 8000
    depends_on:
      - db
    profiles:
      - main
  proxy:
    image: nginx:latest
    volumes:
      - static_files:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf # uses custom nginx conf
      - certs:/app/certs
      - challenges:/app/challenges
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - server
    profiles:
      - main
  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - challenges:/var/www/certbot
    profiles:
      - cert
    command: certonly --webroot -w /var/www/certbot --force-renewal --email email@example.com -d example.com --agree-tos

volumes:
  db_data: # only for data persistence
  static_files: # for accessing static files between the server (build container) and reverse proxy
  certs: # ssl certs
  challenges: # letsencrypt challenges